name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          # Create the private key file and set proper permissions
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          # SSH into EC2 and deploy the code
          ssh -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Change to the application directory on the EC2 instance
            cd /var/www/html
            # Pull the latest changes from the repository
            git pull origin main
            # Example: Restart services or install dependencies (if needed)
            # sudo systemctl restart nginx
            # sudo npm install
          EOF

      - name: Clean up private key
        run: |
          # Remove the private key for security
          rm private_key.pem
